#!/bin/sh

if [ -d "$HOME/.glportal/data" ]; then
    DATAPATH="$HOME/.glportal/data"
else
    BLENDERVERPATH="$HOME/.blender"
fi

help() {
    echo "                                  Asset Linker"
    echo ""
    echo ""
    echo "Links GlPortal data for development."
    echo ""
    echo "Usage: $0 -b blender_version"
    echo "Available Blender versions: "
    ls "$BLENDERVERPATH"
}


getopts "h?vb:" opt
    case "$opt" in
    h|\?)
        help
        exit 0
        ;;
    b)
        if [ -d "$BLENDERVERPATH/$OPTARG" ]; then
            ADDONSPATH="$BLENDERVERPATH/$OPTARG/scripts/addons"
            mkdir -p "$ADDONSPATH"
            DIR=$(CDPATH= cd "$(dirname "$0")" && pwd)
            ln -fs "$DIR/blenderToXmlExport/" "$ADDONSPATH/toGlPortalXml"
        else
            echo "No blender installation found."
            exit 0
        fi

        ;;
    *)
        help
        exit 0
        ;;
    esac
